security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login
            logout_on_user_change : true
            logout:
                path: app_logout
                target: home
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator

    encoders:
        App\Entity\User:
            algorithm: auto

    access_control:
        - { path : ^/idea/add, roles: ROLE_USER }